name: Generate snake game

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake SVG (dark + light)
        uses: Platane/snk/svg-only@v3
        id: snake
        with:
          github_user_name: GuilhermeNerii
          outputs: |
            dist/github-contribution-grid-snake.svg?count=50
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&count=50

      - name: Commit generated files to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
